name: request_permission
description: A flutter plugin for requesting android permissions.
version: 1.0.0
author: Emanuel Oberholzer
homepage: https://gitlab.com/flutterplugins/request_permission

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.u12ampere.request_permission
        pluginClass: RequestPermissionPlugin
